### ISSUE TITLE
`ModelBase.__to_dict__` can infinitely recurse

### ISSUE THREAD

**Issue by bowlingmh** [dgilland/alchy#34]
If a model has a relationship to a model with a backref, `__to_dict__` will recursively try to display the relationship cycle.  

In my own project I solved the problem by using a base inherited from `ModelBase` that overrides `__to_dict__` to skip relationships in recursing.

```
class Base(alchy.ModelBase):
    # Alchy seems broken in its default to_dict implementation
    # It appears to traverse relationships with multiple values, possibly causing
    #  an infinite recursion.  E.g., users have questions and questions have users.
    @property
    def __to_dict__(self):
        keys = super().__to_dict__
        relationships = self.relationships()
        return set(k for k in keys if k not in relationships)
```

**Comment by dgilland** [comment]
This is the expected behavior for to_dict(). The default implementation doesn't guard against recursion. By default it will try to serialize all ORM columns and relationships to the detriment of infinite recursion. Since alchy can't really know when the user wants the serialization to stop, it's on the user to override this when needed.

**Comment by bowlingmh** [comment]
Feel free to close then... this just surprised me.

And thanks for Alchy... has come in very handy for separating SQLAlchemy models from Flask-SQLAlchemy.

**Comment by dgilland** [comment]
You may also want to check out [sqlservice](https://github.com/dgilland/sqlservice) (sort of the next generation of alchy). It's currently not as feature rich as alchy but it does a few things differently that may be useful to you.
